### PR TITLE
Feature/use enumerations instead of ids

### PR DESCRIPTION
**Pull request by green-dragon-pixel**
- added BMP280
- fixed taster inputs to pull-up
- changed numbers to enumation

### CODE REVIEW

**Comment by green-dragon-pixel** [comment]
Dear @Blueforcer, I refactored the code for the controller to use enumerations (to be easier to follow) and added also a BMP280 server.

The code was tested on a live setup with capacitive touch sensors.

**Comment by green-dragon-pixel** [comment]
Dear @Blueforcer, any updates on the active pull requests?

**Comment by xchwarze** [comment]
nice work @green-dragon-pixel !

**Comment by Blueforcer** [comment]
Thanks for your work, i just needed to chnage the library because BMP280_light doesnt exists

**Pull request merged**
